import { IListing } from "@/types";

// Sample data for testing the map and markers
export const mockListings: IListing[] = [
  {
    name: "Prince Hall Grand Lodge",
    address: "1000 U Street NW, Washington, DC 20001",
    street: "1000 U Street NW",
    city: "Washington",
    state: "DC",
    zip: 20001,
    lat: 38.9176,
    lng: -77.0277,
    description: "Prince Hall Grand Lodge of DC",
    place_id: "place_id_1",
    submitted: new Date(),
    claims: [],
    claimsCount: 0,
    imageUri: "https://picsum.photos/640/360",
  },
  {
    name: "Mason's Barbershop",
    address: "1200 H Street NE, Washington, DC 20002",
    street: "1200 H Street NE",
    city: "Washington",
    state: "DC",
    zip: 20002,
    lat: 38.9002,
    lng: -76.9882,
    description: "Quality haircuts by a Prince Hall Mason",
    place_id: "place_id_2",
    submitted: new Date(),
    claims: [],
    claimsCount: 0,
    imageUri: "https://picsum.photos/640/360",
  },
  {
    name: "Square & Compass Cafe",
    address: "500 K Street NW, Washington, DC 20001",
    street: "500 K Street NW",
    city: "Washington",
    state: "DC",
    zip: 20001,
    lat: 38.9032,
    lng: -77.0205,
    description: "Coffee shop owned by a Prince Hall Mason",
    place_id: "place_id_3",
    submitted: new Date(),
    claims: [],
    claimsCount: 0,
    imageUri: "https://picsum.photos/640/360",
  },
  {
    name: "Masonic Auto Repair",
    address: "2000 Rhode Island Ave NE, Washington, DC 20018",
    street: "2000 Rhode Island Ave NE",
    city: "Washington",
    state: "DC",
    zip: 20018,
    lat: 38.9293,
    lng: -76.9770,
    description: "Auto repair shop owned by a Prince Hall Mason",
    place_id: "place_id_4",
    submitted: new Date(),
    claims: [],
    claimsCount: 0,
    imageUri: "https://picsum.photos/640/360",
  },
  {
    name: "Level Construction",
    address: "1500 East Capitol Street NE, Washington, DC 20003",
    street: "1500 East Capitol Street NE",
    city: "Washington",
    state: "DC",
    zip: 20003,
    lat: 38.8898,
    lng: -76.9829,
    description: "Construction company owned by a Prince Hall Mason",
    place_id: "place_id_5",
    submitted: new Date(),
    claims: [],
    claimsCount: 0,
    imageUri: "https://picsum.photos/640/360",
  },
];
